name: Schema Healing
favicon: null
layout_spectrum: 0.44726362358778715
typography_spectrum: 0.03758334391750395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7336817237082869
  lightness: 0.1362605164758861
  saturation: 0.7123254511971027
  rhythmicContrast: 0.001041260315105319
purpose: []
